
[default_session]

[[session]]
name = "Home ğŸ¡"
path = "~/"

[[session]]
name = "Code ğŸ’»"
path = "~/Documents/dev/"
startup_command = "l"

[[session]]
name = "EMP  ğŸ’»"
path = "~/Documents/dev/go/gocb/apps/node/emp/"
startup_command = "l"

[[session]]
name = "Tmux âš™ï¸"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "Neovim âš™ï¸"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "second brain ğŸ§ "
path = "~/c/second-brain"
startup_command = "nvim +ObsidianToday"

[[session]]
name = "Dotfiles"
path = "~/.config"


