
[default_session]


[[session]]
name = "Home ğŸ¡"
path = "~/"

[[session]]
name = "Code ğŸ’»"
path = "~/Documents/dev/"
startup_command = "l"

[[session]]
name = "EMP  ğŸ’»"
path = "~/Documents/dev/go/gocb/apps/node/emp/"
startup_command = "l"


[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "neovim config"
path = "~/.config/nvim"

[[session]]
name = "fish config"
path = "~/.config/fish"
startup_command = "nvim config.fish"

[[session]]
name = "second brain ğŸ§ "
path = "~/c/second-brain"
startup_command = "nvim +ObsidianToday"

[[session]]
name = "sesh config"
path = "~/c/dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "my custom binaries"
path = "~/c/dotfiles/.config/bin"

[[session]]
name = "dotfiles"
path = "~/.config"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
